# -*- mode: python ; coding: utf-8 -*-
"""PyInstaller spec file for RealTV Desktop portable application."""

import sys
import platform
from pathlib import Path

block_cipher = None

PROJECT_ROOT = Path(SPECPATH).parent.parent
SRC_DIR = PROJECT_ROOT / "src"
ASSETS_DIR = PROJECT_ROOT / "assets"
IS_MACOS = platform.system() == "Darwin"

a = Analysis(
    [str(SRC_DIR / "rtv" / "desktop" / "app.py")],
    pathex=[str(PROJECT_ROOT)],
    binaries=[],
    datas=[
        (str(SRC_DIR / "rtv" / "web" / "templates" / "*.html"), "rtv/web/templates"),
        (str(SRC_DIR / "rtv" / "web" / "static" / "*.css"), "rtv/web/static"),
        (str(SRC_DIR / "rtv" / "web" / "static" / "*.svg"), "rtv/web/static"),
        (str(SRC_DIR / "rtv" / "desktop" / "templates" / "*.html"), "rtv/desktop/templates"),
        (str(SRC_DIR / "rtv" / "desktop" / "static" / "*.css"), "rtv/desktop/static"),
        (str(SRC_DIR / "rtv" / "desktop" / "static" / "*.svg"), "rtv/desktop/static"),
        (str(SRC_DIR / "rtv" / "desktop" / "static" / "vendor" / "*.js"), "rtv/desktop/static/vendor"),
        (str(SRC_DIR / "rtv" / "desktop" / "static" / "fonts" / "*.woff2"), "rtv/desktop/static/fonts"),
        (str(SRC_DIR / "rtv" / "desktop" / "static" / "fonts" / "*.ttf"), "rtv/desktop/static/fonts"),
        (str(SRC_DIR / "rtv" / "tui" / "*.tcss"), "rtv/tui"),
        (str(ASSETS_DIR / "logo.png"), "assets"),
    ],
    hiddenimports=[
        "uvicorn.logging",
        "uvicorn.loops",
        "uvicorn.loops.auto",
        "uvicorn.protocols",
        "uvicorn.protocols.http",
        "uvicorn.protocols.http.auto",
        "uvicorn.protocols.websockets",
        "uvicorn.protocols.websockets.auto",
        "uvicorn.lifespan",
        "uvicorn.lifespan.on",
        "sse_starlette",
        "sse_starlette.sse",
        "multipart",
        "multipart.multipart",
        "PlexAPI",
        "plexapi.server",
        "plexapi.playlist",
        "plexapi.video",
        "plexapi.library",
        "plexapi.exceptions",
        "plexapi.gdm",
        "paramiko",
        "textual",
        "rapidfuzz",
        "rapidfuzz.fuzz",
        "pydantic",
        "pydantic_core",
        "pydantic_settings",
        "annotated_types",
        "click",
        "rich",
        "rich.console",
        "rich.progress",
        "yaml",
        "webview",
        "webview.platforms",
        "webview.platforms.winforms",
        "webview.platforms.cocoa",
        "webview.platforms.gtk",
        "webview.platforms.qt",
        "httpx",
        "httpcore",
        "anyio",
        "anyio._backends",
        "anyio._backends._asyncio",
        "h11",
        "sniffio",
        "starlette",
        "starlette.middleware",
        "starlette.requests",
        "starlette.responses",
        "starlette.routing",
        "starlette.staticfiles",
        "starlette.templating",
        "starlette.exceptions",
        "starlette.concurrency",
        "starlette.background",
        "starlette.status",
        "starlette.datastructures",
        "starlette.types",
        "fastapi",
        "fastapi.routing",
        "fastapi.dependencies",
        "fastapi.dependencies.utils",
        "fastapi.encoders",
        "fastapi.exception_handlers",
        "fastapi.logger",
        "fastapi.openapi",
        "fastapi.params",
        "fastapi.types",
        "fastapi.utils",
        "jinja2",
        "jinja2.ext",
    ],
    hookspath=[str(PROJECT_ROOT / "scripts" / "portable")],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        "PyQt5",
        "PyQt6",
        "PySide2",
        "PySide6",
        "tkinter",
        "matplotlib",
        "numpy",
        "pandas",
        "scipy",
        "PIL",
        "pillow",
        "cv2",
        "opencv",
        "torch",
        "tensorflow",
        "keras",
        "pytest",
        "sphinx",
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

if IS_MACOS:
    exe = EXE(
        pyz,
        a.scripts,
        [],
        exclude_binaries=True,
        name="RealTV",
        debug=False,
        bootloader_ignore_signals=False,
        strip=False,
        upx=True,
        console=False,
        disable_windowed_traceback=False,
        argv_emulation=False,
        target_arch=None,
        codesign_identity=None,
        entitlements_file=None,
    )
    coll = COLLECT(
        exe,
        a.binaries,
        a.zipfiles,
        a.datas,
        strip=False,
        upx=True,
        upx_exclude=[],
        name="RealTV",
    )
    app = BUNDLE(
        coll,
        name="RealTV.app",
        icon=None,
        bundle_identifier="com.plexrealtv.desktop",
        version="0.3.0",
    )
else:
    exe = EXE(
        pyz,
        a.scripts,
        a.binaries,
        a.zipfiles,
        a.datas,
        [],
        name="RealTV",
        debug=False,
        bootloader_ignore_signals=False,
        strip=False,
        upx=True,
        upx_exclude=[],
        runtime_tmpdir=None,
        console=True,  # Enable console for debugging
        disable_windowed_traceback=False,
        argv_emulation=False,
        target_arch=None,
        codesign_identity=None,
        entitlements_file=None,
        icon=str(ASSETS_DIR / "logo.ico") if (ASSETS_DIR / "logo.ico").exists() else None,
    )
